//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime time { get; set; }
        public string AspNetUsersId { get; set; }
        public int ConsaltantId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Consaltant Consaltant { get; set; }
    }
}
